# Generated by Django 5.2.6 on 2025-09-25 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0002_aviso'),
        ('finanzas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='usuario',
        ),
        migrations.AddField(
            model_name='gasto',
            name='anio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gasto',
            name='mes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='finanzas.reserva'),
        ),
        migrations.AddField(
            model_name='pago',
            name='residente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='usuarios.residente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='residente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='usuarios.residente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='finanzas.gasto'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterUniqueTogether(
            name='gasto',
            unique_together={('propiedad', 'mes', 'anio')},
        ),
    ]
