# Generated by Django 5.2.6 on 2025-09-26 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_remove_pago_usuario_remove_reserva_fecha_creacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasto',
            options={'ordering': ('-anio', '-mes', 'propiedad_id')},
        ),
        migrations.RemoveField(
            model_name='pago',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='reserva',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='residente',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='residente',
        ),
        migrations.AddField(
            model_name='pago',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gasto',
            name='anio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha_emision',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='mes',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='gasto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='finanzas.gasto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
