# Generated by Django 5.2.6 on 2025-09-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0002_aviso'),
        ('finanzas', '0003_alter_gasto_options_remove_pago_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gasto',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['propiedad', 'mes', 'anio'], name='finanzas_ga_propied_fae357_idx'),
        ),
    ]
