# Generated by Django 5.2.6 on 2025-09-26 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_alter_gasto_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ('-fecha_pago',)},
        ),
        migrations.RemoveIndex(
            model_name='gasto',
            name='finanzas_ga_propied_fae357_idx',
        ),
        migrations.AlterField(
            model_name='pago',
            name='gasto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='finanzas.gasto'),
        ),
    ]
