# Generated by Django 5.2.6 on 2025-09-26 05:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0002_aviso'),
        ('finanzas', '0005_alter_pago_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={},
        ),
        migrations.AlterField(
            model_name='pago',
            name='gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='finanzas.gasto'),
        ),
        migrations.AlterUniqueTogether(
            name='gasto',
            unique_together={('propiedad', 'mes', 'anio', 'descripcion', 'monto')},
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('pagado', models.BooleanField(default=False)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='condominio.propiedad')),
            ],
            options={
                'ordering': ('-fecha_emision', 'propiedad_id'),
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='multa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='finanzas.multa'),
        ),
    ]
