# Generated by Django 5.2.6 on 2025-09-26 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_alter_pago_options_alter_pago_gasto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multa',
            options={'ordering': ('-anio', '-mes', 'propiedad_id')},
        ),
        migrations.AlterUniqueTogether(
            name='gasto',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pago',
            name='multa',
        ),
        migrations.AddField(
            model_name='multa',
            name='anio',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multa',
            name='concepto',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AddField(
            model_name='multa',
            name='mes',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='multa',
            name='fecha_emision',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pago',
            name='gasto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='finanzas.gasto'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PagoMulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes_multas/')),
                ('multa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='finanzas.multa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_multas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
