# Generated by Django 5.2.6 on 2025-09-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_alter_multa_options_alter_gasto_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='concepto',
            field=models.CharField(blank=True, default='General', max_length=255),
        ),
    ]
