# Generated by Django 5.2.6 on 2025-09-28 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0009_pago_estado_pago_pago_id_transaccion_pasarela_and_more'),
        ('mantenimiento', '0004_alter_personalmantenimiento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('MANTENIMIENTO', 'Mantenimiento y Reparaciones'), ('SERVICIOS', 'Servicios Públicos (Agua, Luz)'), ('SUELDOS', 'Sueldos y Salarios'), ('ADMIN', 'Gastos Administrativos'), ('LIMPIEZA', 'Limpieza y Jardinería'), ('SEGURIDAD', 'Seguridad'), ('OTROS', 'Otros')], max_length=20)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes_egresos/')),
                ('solicitud_mantenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos', to='mantenimiento.solicitudmantenimiento')),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('pago_relacionado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingreso_manual', to='finanzas.pago')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-fecha'],
            },
        ),
    ]
