# Generated by Django 5.2.6 on 2025-09-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_alter_devicetoken_options_alter_devicetoken_platform_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetoken',
            options={'verbose_name': 'Dispositivo (token push)', 'verbose_name_plural': 'Dispositivos (tokens push)'},
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=10),
        ),
    ]
