# Generated by Django 5.2.6 on 2025-10-02 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0004_alter_regla_options_alter_propiedad_propietario'),
        ('usuarios', '0008_auto_20250930_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aviso',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name': 'Aviso', 'verbose_name_plural': 'Avisos'},
        ),
        migrations.AddField(
            model_name='aviso',
            name='activo',
            field=models.BooleanField(default=True, help_text='Determina si el aviso está activo y visible'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='dirigido_a',
            field=models.CharField(choices=[('TODOS', 'Todos los residentes'), ('PROPIETARIOS', 'Solo propietarios'), ('INQUILINOS', 'Solo inquilinos')], default='TODOS', help_text='A quién está dirigido el aviso', max_length=20),
        ),
        migrations.CreateModel(
            name='LecturaAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lectura', models.DateTimeField(auto_now_add=True)),
                ('ip_lectura', models.GenericIPAddressField(blank=True, help_text='IP desde donde se leyó el aviso', null=True)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='condominio.aviso')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_leidos', to='usuarios.residente')),
            ],
            options={
                'verbose_name': 'Lectura de Aviso',
                'verbose_name_plural': 'Lecturas de Avisos',
                'ordering': ['-fecha_lectura'],
                'unique_together': {('aviso', 'residente')},
            },
        ),
    ]
