# Generated by Django 5.2.6 on 2025-09-28 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0004_alter_regla_options_alter_propiedad_propietario'),
        ('usuarios', '0003_alter_residente_usuario_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residente',
            name='propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residentes', to='condominio.propiedad'),
        ),
    ]
