# Generated by Django 5.2.6 on 2025-09-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_residente_propiedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='face_id_aws',
            field=models.CharField(blank=True, help_text='ID único del rostro asignado por AWS Rekognition.', max_length=255, null=True, unique=True),
        ),
    ]
