# Generated by Django 5.2.6 on 2025-09-30 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_residente_face_id_aws'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PROPIETARIO', 'Propietario (Admin)'), ('RESIDENTE', 'Residente (Inquilino)'), ('SEGURIDAD', 'Personal de Seguridad'), ('MANTENIMIENTO', 'Personal de Mantenimiento')], default='RESIDENTE', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
