# Generated by Django 5.2.6 on 2025-09-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('ELECTRICIDAD', 'Electricista'), ('PLOMERIA', 'Plomero'), ('JARDINERIA', 'Jardinería'), ('PINTURA', 'Pintura'), ('LIMPIEZA', 'Limpieza'), ('CARPINTERIA', 'Carpintería'), ('AIRES', 'Aire Acondicionado'), ('GENERAL', 'Mantenimiento General')], help_text='Especialidad (solo para personal de mantenimiento)', max_length=50, null=True),
        ),
    ]
