# Generated by Django 5.2.6 on 2025-09-30 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_userprofile_especialidad'),
    ]

    operations = [
    ]
