# Generated by Django 5.2.6 on 2025-09-25 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0002_aviso'),
        ('mantenimiento', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudmantenimiento',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudmantenimiento',
            name='propiedad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_mantenimiento', to='condominio.propiedad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudmantenimiento',
            name='solicitado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_mantenimiento', to='usuarios.residente'),
            preserve_default=False,
        ),
    ]
