# Generated by Django 5.2.6 on 2025-09-26 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_alter_solicitudmantenimiento_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalmantenimiento',
            options={'ordering': ['nombre'], 'verbose_name': 'Personal de mantenimiento', 'verbose_name_plural': 'Personal de mantenimiento'},
        ),
        migrations.AlterModelOptions(
            name='solicitudmantenimiento',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Solicitud de mantenimiento', 'verbose_name_plural': 'Solicitudes de mantenimiento'},
        ),
        migrations.RemoveField(
            model_name='personalmantenimiento',
            name='usuario',
        ),
        migrations.AddField(
            model_name='personalmantenimiento',
            name='nombre',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalmantenimiento',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='solicitudmantenimiento',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='personalmantenimiento',
            name='especialidad',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='solicitudmantenimiento',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_asignados', to='mantenimiento.personalmantenimiento'),
        ),
        migrations.AlterField(
            model_name='solicitudmantenimiento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='solicitudmantenimiento',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADO', 'Asignado'), ('EN_PROCESO', 'En proceso'), ('RESUELTO', 'Resuelto'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudmantenimiento',
            name='solicitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_mantenimiento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudmantenimiento',
            name='titulo',
            field=models.CharField(max_length=160),
        ),
    ]
