# Generated by Django 5.2.6 on 2025-09-26 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_alter_personalmantenimiento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalmantenimiento',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='solicitudmantenimiento',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterField(
            model_name='solicitudmantenimiento',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos', to='mantenimiento.personalmantenimiento'),
        ),
        migrations.AlterField(
            model_name='solicitudmantenimiento',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudmantenimiento',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
