# Generated by Django 5.2.6 on 2025-10-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_alter_personalmantenimiento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmantenimiento',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se resolvió la solicitud', null=True),
        ),
        migrations.AddField(
            model_name='solicitudmantenimiento',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], db_index=True, default='MEDIA', max_length=20),
        ),
    ]
