# Generated by Django 5.2.6 on 2025-09-26 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0002_aviso'),
        ('seguridad', '0002_rename_documento_identidad_visitante_documento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ('-fecha_ingreso_programado',)},
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='condominio.propiedad'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='seguridad.visitante'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='nombre_completo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
