# Generated by Django 5.2.6 on 2025-09-28 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_alter_visita_options_alter_vehiculo_placa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_evento', models.CharField(choices=[('INGRESO', 'Ingreso Vehicular'), ('SALIDA', 'Salida Vehicular')], max_length=10)),
                ('placa_detectada', models.CharField(help_text='La matrícula tal como fue detectada por la IA.', max_length=20)),
                ('accion', models.CharField(choices=[('PERMITIDO', 'Acceso Permitido'), ('DENEGADO', 'Acceso Denegado')], max_length=10)),
                ('motivo', models.CharField(help_text="Razón por la que se tomó la acción (ej. 'Placa no encontrada').", max_length=255)),
                ('vehiculo_registrado', models.ForeignKey(blank=True, help_text='Vehículo correspondiente en la base de datos, si existe.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.vehiculo')),
            ],
            options={
                'verbose_name': 'Evento de Seguridad IA',
                'verbose_name_plural': 'Eventos de Seguridad IA',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
