# Generated by Django 5.2.6 on 2025-09-28 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0004_eventoseguridad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('rtsp_url', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deteccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_id', models.CharField(blank=True, default='', max_length=100)),
                ('similarity', models.FloatField(blank=True, null=True)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('frame', models.ImageField(blank=True, upload_to='detecciones/%Y/%m/%d/')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detecciones', to='seguridad.camera')),
                ('matched_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
    ]
