# Generated by Django 5.2.6 on 2025-10-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0005_camera_deteccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En Curso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PROGRAMADA', max_length=20),
        ),
    ]
